assignment_handler/urls.py
from django.urls import path

from .views import (
    index,
    WorkerDetailView,
    WorkerCreate,
    WorkerUpdate,
    WorkerDelete,
    WorkersListView,
    TeamDetailView,
    TeamCreate,
    TeamUpdate,
    TeamDelete,
    PositionListView,
    PositionCreate,
    PositionUpdate,
    PositionDelete,
    TaskDetailView,
    TaskCreate,
    TaskUpdate,
    TaskDelete,
    TaskTypeListView,
    TaskTypeCreate,
    TaskTypeUpdate,
    TaskTypeDelete,
    ProjectDetailView,
    ProjectCreate,
    ProjectUpdate,
    ProjectDelete,
    ProjectCategoryListView,
    ProjectCategoryCreate,
    ProjectCategoryUpdate,
    ProjectCategoryDelete,
    DashboardView,
    TaskPanelView,
    ProjectTrackingPanelView,
    ToggleAssignTaskView,
    ToggleTeamTransitionView,
    SwitchTeamView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "accounts/register/",
        WorkerCreate.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdate.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDelete.as_view(),
        name="worker-delete"
    ),
    path(
        "workers_list/",
        WorkersListView.as_view(),
        name="workers-list"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreate.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdate.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDelete.as_view(),
        name="position-delete"
    ),
    path(
        "teams/<pk>/",
        TeamDetailView.as_view(),
        name="team-detail"
    ),
    path(
        "teams/create/",
        TeamCreate.as_view(),
        name="team-create"
    ),
    path(
        "teams/<int:pk>/update/",
        TeamUpdate.as_view(),
        name="team-update"
    ),
    path(
        "teams/<int:pk>/delete",
        TeamDelete.as_view(),
        name="team-delete"
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/create/",
        TaskCreate.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdate.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDelete.as_view(),
        name="task-delete"
    ),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreate.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdate.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDelete.as_view(),
        name="task-type-delete"
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/create/",
        ProjectCreate.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:pk>/update",
        ProjectUpdate.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:pk>/delete",
        ProjectDelete.as_view(),
        name="project-delete"
    ),
    path(
        "project-categories/",
        ProjectCategoryListView.as_view(),
        name="project-category-list",
    ),
    path(
        "project-categories/create/",
        ProjectCategoryCreate.as_view(),
        name="project-category-create",
    ),
    path(
        "project-categories/<int:pk>/update/",
        ProjectCategoryUpdate.as_view(),
        name="project-category-update",
    ),
    path(
        "project-categories/<int:pk>/delete/",
        ProjectCategoryDelete.as_view(),
        name="project-category-delete",
    ),
    path(
        "dashboard/",
        DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        "task_panel/",
        TaskPanelView.as_view(),
        name="task-panel"
    ),
    path(
        "project_tracking_panel/",
        ProjectTrackingPanelView.as_view(),
        name="project-tracking-panel",
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        ToggleAssignTaskView.as_view(),
        name="toggle-task-assign",
    ),
    path(
        "teams/<int:pk>/toggle-add/<int:team_id>/",
        ToggleTeamTransitionView.as_view(),
        name="toggle-team-transition",
    ),
    path(
        "teams/<int:pk>/switch/<str:action>/",
        SwitchTeamView.as_view(),
        name="switch-team",
    ),
]

app_name = "assignment_handler"

workflow_organizer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("assignment_handler.urls", namespace="assignment_handler")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

assignment_handler/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import QuerySet, Q, Count
from taggit.managers import TaggableManager


class Position(models.Model):
    name = models.CharField(max_length=255, unique=True)
    duties = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.name

    def duties_to_a_list(self) -> list:
        return list(self.duties.split(";"))[:-1]


class Team(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name

    def sum_of_budget(self) -> int:
        return sum(project.budget for project in self.projects.all())

    def add_member(self, user):
        self.members.add(user)

    def remove_member(self, user):
        self.members.remove(user)


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        related_name="workers",
        blank=True,
        null=True,
    )
    teams = models.ManyToManyField(
        Team,
        related_name="members",
        blank=True,
    )
    rating_points = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"

    def completed_tasks(self) -> QuerySet:
        return (
            self.tasks.annotate(assignees_count=Count("assignees"))
            .filter(is_completed=True, assignees_count__gt=0)
            .distinct()
        )

    def underway_tasks(self) -> QuerySet:
        return (
            self.tasks.annotate(assignees_count=Count("assignees"))
            .filter(Q(is_completed=False) & Q(assignees_count__gt=0))
            .distinct()
        )


class WorkerEvaluation(models.Model):
    SCORE_CHOICES = (
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5"),
    )
    evaluator = models.ForeignKey(
        Worker, on_delete=models.CASCADE, related_name="reviews_by"
    )
    worker = models.ForeignKey(
        Worker, on_delete=models.CASCADE, related_name="reviews_of"
    )
    score = models.IntegerField(choices=SCORE_CHOICES)


class ProjectCategory(models.Model):
    name = models.CharField(max_length=255, unique=True)
    depiction = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = "project categories"


class Project(models.Model):
    PRIORITY_CHOICES = [("U", "Urgent"), ("A", "Average"), ("S", "Side-tracked")]

    name = models.CharField(max_length=255)
    depiction = models.TextField()
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, default="S")
    time_constraints = models.DateField()
    project_category = models.ForeignKey(
        ProjectCategory,
        on_delete=models.CASCADE,
        related_name="projects",
    )
    team = models.ForeignKey(
        Team, on_delete=models.CASCADE, blank=True, null=True, related_name="projects"
    )
    budget = models.DecimalField(decimal_places=2, max_digits=8, default=0)
    funds_used = models.DecimalField(
        decimal_places=2, max_digits=8, default=0, blank=True
    )
    tags = TaggableManager(blank=True)

    def get_project_progress(self):
        total_progress = 0
        number_of_blocks = 0
        blocks = self.projectblock_set.all()

        for block in blocks:
            block_progress = block.get_block_progress()
            total_progress += block_progress
            number_of_blocks += 1

        if number_of_blocks > 0:
            avg_progress = total_progress / number_of_blocks
        else:
            avg_progress = 0

        return round(avg_progress, 2)

    def get_current_phase(self):
        if self.get_project_progress() == 0:
            return "Initiation and planning phase"
        elif 0 < self.get_project_progress() < 100:
            return "Execution phase"
        elif self.get_project_progress() == 100:
            return "Implementation and closure phase"
        else:
            return "Unknown phase"

    def __str__(self) -> str:
        return self.name


class ProjectBlock(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    depiction = models.TextField()
    total_tasks = models.PositiveIntegerField(null=False, blank=False)
    completed_tasks = models.PositiveIntegerField(default=0)

    @staticmethod
    def predefined_blocks():
        return [
            {"name": "Frontend development", "index": 0},
            {"name": "Backend development", "index": 1},
            {"name": "Database/data layer", "index": 2},
            {"name": "Testing", "index": 3},
            {"name": "Infrastructure setup", "index": 4},
            {"name": "Documentation", "index": 5},
            {"name": "UX/design", "index": 6},
        ]

    def get_block_progress(self):
        if self.total_tasks > 0:
            return round((self.completed_tasks / self.total_tasks) * 100, 2)
        else:
            return 0.00

    def __str__(self) -> str:
        return f"Project name: {self.project} (project block: {self.name})"


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)
    depiction = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    PRIORITY_CHOICES = [("U", "Urgent"), ("A", "Average"), ("S", "Side-tracked")]

    name = models.CharField(max_length=255)
    depiction = models.TextField()
    time_constraints = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, default="S")
    task_type = models.ForeignKey(
        TaskType, on_delete=models.CASCADE, related_name="tasks"
    )
    assignees = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="tasks", blank=True
    )
    tags = TaggableManager(blank=True)

    def tags_remained(self) -> int:
        count = self.tags.count() - 1
        return count if count > 0 else 0

    def __str__(self) -> str:
        return f"{self.name} (priority: {self.priority})"

templates/assignment_handler/project_category_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Projects management {% endblock %}

{% block content %}

{% include "includes/sidebar.html" %}

  <div class="row">
    <header>
      <div class="page-header min-height-300">
        <span class="mask bg-gradient-blue opacity-6"></span>
      </div>
    </header>
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
      <section class="py-sm-7 py-5 position-relative">
        <div class="container">
          <div class="row">
            <div class="col-12 mx-auto">
              <div style="height: 40px;"></div>
              <div style="float: right" class="mt-n6">
                {% include "includes/search_form.html" %}
              </div>
              <br><br>
              <div class="row py-5">
                <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto mb-4">
                  <div class="d-flex justify-content-between align-items-center">
                    <h2 class="mb-4 font-weight-bold">Project categories</h2>
                    <div class="row">
                      <a style="width: 40px; height: 40px; box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" href="{% url 'assignment_handler:project-category-create' %}" class="btn btn-white mx-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square my-colored-icon" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                          <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                        </svg>
                      </a>
                    </div>
                  </div>
                  <br>
                  {% if project_category_list %}
                    {% for project_category in project_category_list %}
                      <div style="width:100%; box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" class="card mb-3">
                        <div class="card-body">
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="card-title"><h5><i>#{{ project_category.name }}</i></h5></div>
                            <div class="row">
                              <a style="width: 40px; height: 40px; box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" href="{% url 'assignment_handler:project-category-update' pk=project_category.id %}" class="btn btn-white mx-3">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill my-colored-pen" viewBox="0 0 16 16">
                                  <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
                                </svg>
                              </a>
                              <a style="width: 40px; height: 40px; box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" href="{% url 'assignment_handler:project-category-delete' pk=project_category.id %}" class="btn btn-white mx-3">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill my-colored-can" viewBox="0 0 16 16">
                                  <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                                </svg>
                              </a>
                            </div>
                          </div>
                          <div class="card-text"><p class="text-sm">{{ project_category.depiction }}</p></div>
                        </div>
                      </div>
                    {% endfor %}
                  {% else %}
                    <p>There are no project categories yet!</p>
                  {% endif %}
                  {% include 'includes/pagination.html' %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

{% endblock content %}

templates/assignment_handler/task_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ task.name }} {% endblock %}

{% block content %}

{% include "includes/sidebar.html" %}

  <div class="row">
    <header>
      <div class="page-header min-height-300" style="background-image: url({% static 'img/backgrounds/task-detail.jpeg' %});">
        <span class="mask bg-gradient-dark opacity-6"></span>
      </div>
    </header>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
      <section class="py-sm-7 py-5 position-relative mt-3">
        <div class="container">
          <div class="row">
            <div class="col-12 mx-auto">
              <div class="col-lg-9 col-md-9 z-index-2 position-relative px-md-1 px-sm-5 mx-auto mb-2">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <h3 class="mb-2 font-weight-bold assignment-name">{{ task.name }}</h3>
                  <li style="box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" class="card dropdown dropdown-hover mx-2">
                    <a class="my-2 mx-3 d-flex cursor-pointer align-items-center" id="dropdownMenuDocs" data-bs-toggle="dropdown" aria-expanded="false">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-button-wide" viewBox="0 0 16 16">
                        <path d="M0 1.5A1.5 1.5 0 0 1 1.5 0h13A1.5 1.5 0 0 1 16 1.5v2A1.5 1.5 0 0 1 14.5 5h-13A1.5 1.5 0 0 1 0 3.5v-2zM1.5 1a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5h-13z"/>
                        <path d="M2 2.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5zm10.823.323-.396-.396A.25.25 0 0 1 12.604 2h.792a.25.25 0 0 1 .177.427l-.396.396a.25.25 0 0 1-.354 0zM0 8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V8zm1 3v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2H1zm14-1V8a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2h14zM2 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
                      </svg>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-animation dropdown-md dropdown-md-responsive mt-0 mt-lg-3 p-3 border-radius-lg" aria-labelledby="dropdownMenuDocs">
                      <div class="d-none d-lg-block">
                        <ul class="list-group">
                          <li class="nav-item list-group-item border-0 p-0">
                            <a class="dropdown-item py-2 ps-3 border-radius-md" target="_blank" href="{% url 'assignment_handler:task-update' pk=task.id %}">
                              <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Edit task</h6>
                            </a>
                          </li>
                          <li class="nav-item list-group-item border-0 p-0">
                            <a class="dropdown-item py-2 ps-3 border-radius-md" target="_blank" href="{% url 'assignment_handler:task-delete' pk=task.id %}">
                              <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Delete task</h6>
                            </a>
                          </li>
                        </ul>
                      </div>
                    </ul>
                  </li>
                </div>
                <table class="mx-n2 table table-borderless">
                  <thead>
                    <tr>
                      <td></td>
                      <td></td>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td class="header-name"><i>Priority</i></td>
                      <td>
                        {% if task.priority in "U" %}
                          <span class="badge bg-danger text-uppercase fw-semibold">{{ task.get_priority_display }}</span>
                        {% elif task.priority in "A" %}
                          <span class="badge bg-warning text-uppercase fw-semibold">{{ task.get_priority_display }}</span>
                        {% else %}
                          <span class="badge bg-success text-uppercase fw-semibold">{{ task.get_priority_display }}</span>
                        {% endif %}
                      </td>
                    </tr>
                    <tr>
                      <td class="header-name"><i>Status</i></td>
                      <td>{% if not task.is_completed and task.assignees.count > 0 %}Underway{% elif task.is_completed %}Completed{% else %}Queue{% endif %}</td>
                    </tr>
                    <tr>
                      <td class="header-name"><i>Assignees</i></td>
                      <td>
                        <div class="dropdown">
                          <div class="list-unstyled">
                            {% for assignee in task.assignees.all %}
                              <div class="list-item mb-2" >
                                <a href="{% url 'assignment_handler:worker-detail' pk=assignee.id %}"
                                 class="text-muted avatar-sm text-decoration-none"
                                 title="{{ assignee.first_name }} {{ assignee.last_name }}">
                                 <img style="border-radius: 50% !important; object-fit: cover; width: 50px; height: 50px;"
                                      src="{% static 'img/team/'|add:assignee.username|add:'.jpeg' %}"
                                      id="avatar-{{ worker.id }}"
                                      onerror="placeholderAvatar(this)">
                                 <p style="margin: 5px; display: inline">{{ assignee.first_name }} {{assignee.last_name }}</p>
                                </a>
                              </div>
                            {% endfor %}
                            <div class="list-item mb-2">
                              {% if task in user.tasks.all %}
                                <a href="{% url 'assignment_handler:toggle-task-assign' pk=task.id %}" class="text-muted text-decoration-none" >
                                  <svg style="margin: 0 3px 4px 7px" xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-slash" viewBox="0 0 16 16">
                                    <path d="M13.879 10.414a2.501 2.501 0 0 0-3.465 3.465l3.465-3.465Zm.707.707-3.465 3.465a2.501 2.501 0 0 0 3.465-3.465Zm-4.56-1.096a3.5 3.5 0 1 1 4.949 4.95 3.5 3.5 0 0 1-4.95-4.95ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm.256 7a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
                                  </svg>
                                  <i class="text-sm order-message">Remove me</i>
                                </a>
                              {% else %}
                                <a href="{% url 'assignment_handler:toggle-task-assign' pk=task.id %}" class="text-muted text-decoration-none" >
                                  <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16">
                                    <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
                                    <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
                                  </svg>
                                  <i class="text-sm order-message">Add me</i>
                                </a>
                              {% endif %}
                            </div>
                          </div>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td class="header-name"><i>Drop dead date</i></td>
                      <td>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                          <path fill="red" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                          <path fill="red" d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                        </svg>
                        <span>{{ task.time_constraints }}</span>
                        {% if passed_deadline %}
                          <span class="task-deadline" style="margin-left: 10px;">The task is overdue!</span>
                        {% endif %}
                      </td>
                    </tr>
                    <tr>
                      <td class="header-name"><i>Task type</i></td>
                      <td>
                        <i class="text-primary">#{{ task.task_type }}</i>
                      </td>
                    </tr>
                    <tr>
                      {% if task.tags.all %}
                        <td class="text-muted header-name"><i>Tags</i></td>
                        <td>
                          <div class="dropdown">
                            {% for tag in task.tags.all %}
                              <a
                              style="color: white; background-color: rgb(2, 124, 199); border: 1px solid rgba(60, 199, 255, .2); font-size:10px; height:22px; padding:3px 3px; margin: 0"
                              class="btn button-sm fw-semibold"
                              href="{% url 'assignment_handler:task-panel' %}?tag={{ tag.name | urlencode }}">
                              {{ tag.name }}
                              </a>
                            {% endfor %}
                          </div>
                        </td>
                      {% endif %}
                    </tr>
                  </tbody>
                </table>
                <hr class="hr mb-4" style="border-bottom: 1px solid rgba(0, 0, 0, .5)">
                <div class="row mb-4">
                  <h5 class="h5">Depiction</h5>
                  <p style="font-size: 17px;">{{ task.depiction }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <script>
          function placeholderAvatar(img) {
            img.src = "{% static 'img/team/avatar-placeholder.jpeg' %}";
          }
        </script>
      </section>
    </div>
  </div>

{% endblock content %}