assignment_handler/urls.py
from django.urls import path

from .views import (
    index,
    WorkerDetailView,
    WorkerCreate,
    WorkerUpdate,
    WorkerDelete,
    WorkersListView,
    TeamDetailView,
    TeamCreate,
    TeamUpdate,
    TeamDelete,
    PositionListView,
    PositionCreate,
    PositionUpdate,
    PositionDelete,
    TaskDetailView,
    TaskCreate,
    TaskUpdate,
    TaskDelete,
    TaskTypeListView,
    TaskTypeCreate,
    TaskTypeUpdate,
    TaskTypeDelete,
    ProjectDetailView,
    ProjectCreate,
    ProjectUpdate,
    ProjectDelete,
    ProjectCategoryListView,
    ProjectCategoryCreate,
    ProjectCategoryUpdate,
    ProjectCategoryDelete,
    DashboardView,
    TaskPanelView,
    ProjectTrackingPanelView,
    ToggleAssignTaskView,
    ToggleTeamTransitionView,
    SwitchTeamView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "accounts/register/",
        WorkerCreate.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdate.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDelete.as_view(),
        name="worker-delete"
    ),
    path(
        "workers_list/",
        WorkersListView.as_view(),
        name="workers-list"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreate.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdate.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDelete.as_view(),
        name="position-delete"
    ),
    path(
        "teams/<pk>/",
        TeamDetailView.as_view(),
        name="team-detail"
    ),
    path(
        "teams/create/",
        TeamCreate.as_view(),
        name="team-create"
    ),
    path(
        "teams/<int:pk>/update/",
        TeamUpdate.as_view(),
        name="team-update"
    ),
    path(
        "teams/<int:pk>/delete",
        TeamDelete.as_view(),
        name="team-delete"
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/create/",
        TaskCreate.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdate.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDelete.as_view(),
        name="task-delete"
    ),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreate.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdate.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDelete.as_view(),
        name="task-type-delete"
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/create/",
        ProjectCreate.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:pk>/update",
        ProjectUpdate.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:pk>/delete",
        ProjectDelete.as_view(),
        name="project-delete"
    ),
    path(
        "project-categories/",
        ProjectCategoryListView.as_view(),
        name="project-category-list",
    ),
    path(
        "project-categories/create/",
        ProjectCategoryCreate.as_view(),
        name="project-category-create",
    ),
    path(
        "project-categories/<int:pk>/update/",
        ProjectCategoryUpdate.as_view(),
        name="project-category-update",
    ),
    path(
        "project-categories/<int:pk>/delete/",
        ProjectCategoryDelete.as_view(),
        name="project-category-delete",
    ),
    path(
        "dashboard/",
        DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        "task_panel/",
        TaskPanelView.as_view(),
        name="task-panel"
    ),
    path(
        "project_tracking_panel/",
        ProjectTrackingPanelView.as_view(),
        name="project-tracking-panel",
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        ToggleAssignTaskView.as_view(),
        name="toggle-task-assign",
    ),
    path(
        "teams/<int:pk>/toggle-add/<int:team_id>/",
        ToggleTeamTransitionView.as_view(),
        name="toggle-team-transition",
    ),
    path(
        "teams/<int:pk>/switch/<str:action>/",
        SwitchTeamView.as_view(),
        name="switch-team",
    ),
]

app_name = "assignment_handler"

workflow_organizer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("assignment_handler.urls", namespace="assignment_handler")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class="row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
             <h6 class="text-gradient text-primary font-weight-bolder d-flex flex-column"> <div>Assignments monitoring and tackling</div> <div class="align-self-center">system</div> </h6>
          </div>
          <div>
            <h6 class="mt-3 mb-2 opacity-8">Social</h6>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim/" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
                  <i class="fab fa-dribbble text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
                  <i class="fab fa-youtube text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/presentation" target="_blank">
                  About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/templates/free" target="_blank">
                  Freebies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/templates/premium" target="_blank">
                  Premium Tools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/blog" target="_blank">
                  Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Resources</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://iradesign.io/" target="_blank">
                  Illustrations
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/bits" target="_blank">
                  Bits & Snippets
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/affiliates/new" target="_blank">
                  Affiliate Program
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Help & Support</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/contact-us" target="_blank">
                  Contact Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center" target="_blank">
                  Knowledge Center
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://services.creative-tim.com/?ref=ct-soft-ui-footer" target="_blank">
                  Custom Development
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/sponsorships" target="_blank">
                  Sponsorships
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-gradient text-primary text-sm">Legal</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/terms" target="_blank">
                  Terms & Conditions
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/privacy" target="_blank">
                  Privacy Policy
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/license" target="_blank">
                  Licenses (EULA)
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Assignments monitoring and tackling system by &copy; <a target="_blank" href="" target="_blank">Progress personally</a>
              - Coded by <a target="_blank" href="" target="_blank">Anonymus</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/pagination.html
{% if is_paginated %}
  <div class="container">
    <div class="row justify-space-between py-2">
      <div class="col-lg-4 mx-auto">
      {% if page_obj.paginator.num_pages > 1 %}
  <ul class="pagination pagination-primary m-4">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}&page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
        </a>
      </li>
    {% endif %}
    <li class="page-item active">
      <a class="page-link" href="javascript:;">{{ page_obj.number }}</a>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}&page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}
      </div>
    </div>
  </div>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}

<form style="display:flex" action="" method="get">
  {{ search_form|crispy }}
  <input style="width: 100px; !important flex: 1;" class="mx-2 btn btn-outline-secondary fw-semibold" type="submit" value="Search">
</form>

templates/includes/sidebar.html
{% load static %}

{% block css_additional %}

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

{% endblock %}

  <div class="container position-sticky z-index-sticky top-1" style="width: 100%">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <a class="navbar-brand font-weight-bolder ms-sm-3 fs-5" href="/" rel="tooltip" data-placement="bottom">
              Assignments monitoring and tackling system
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100 " id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto align-items-center">
                {% if user.is_authenticated %}
                  <li class="nav-item dropdown dropdown-hover mx-1">
                    <a class="nav-link font-weight-bolder ps-2 d-flex cursor-pointer align-items-center fs-7"
                       href="{% url 'assignment_handler:task-panel' %}">
                      Task panel
                    </a>
                  </li>
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-4 ms-3" href="{% url 'assignment_handler:project-tracking-panel' %}" target="_blank">
                     <p class="d-inline text-sm z-index-1 font-weight-bolder fs-7" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Get Sources">Project tracking panel</p>
                    </a>
                  </li>
                  <li class="nav-item dropdown dropdown-hover mx-1">
                    <a class="nav-link font-weight-bolder ps-2 d-flex cursor-pointer align-items-center fs-7" id="dropdownMenuDocs" data-bs-toggle="dropdown" aria-expanded="false">
                      Parameters management
                      <i class="fa fa-chevron-down ms-1 fa-xs"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-animation dropdown-md dropdown-md-responsive mt-0 mt-lg-3 p-3 border-radius-lg" aria-labelledby="dropdownMenuDocs">
                      <div class="d-none d-lg-block">
                        <ul class="list-group">
                          <li class="nav-item list-group-item border-0 p-0">
                            <a class="dropdown-item py-2 ps-3 border-radius-md" target="_blank" href="{% url 'assignment_handler:task-type-list' %}">
                              <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Task type management</h6>
                              <span class="regular-font-type text-sm">Set up or edit task types</span>
                            </a>
                          </li>
                          <li class="nav-item list-group-item border-0 p-0">
                            <a class="dropdown-item py-2 ps-3 border-radius-md" target="_blank" href="{% url 'assignment_handler:project-category-list' %}">
                              <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Project categories management</h6>
                              <span class="regular-font-type text-sm">Create or rearrange project categories</span>
                            </a>
                          </li>
                          <li class="nav-item list-group-item border-0 p-0">
                            <a class="dropdown-item py-2 ps-3 border-radius-md" target="_blank" href="{% url 'assignment_handler:position-list' %}">
                              <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Positions management</h6>
                              <span class="regular-font-type text-sm">Look over or edit positions</span>
                            </a>
                          </li>
                        </ul>
                      </div>
                    </ul>
                  </li>
                {% endif %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-4 ms-3" href="{% url 'assignment_handler:dashboard' %}" target="_blank">
                    <p class="d-inline text-sm z-index-1 font-weight-bolder fs-7" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Get Sources">Dashboard</p>
                  </a>
                </li>
                  {% if user.is_authenticated %}
                     <li class="nav-item ms-lg-auto">
                      <a class="nav-link nav-link-icon me-2"
                        href="{% url 'assignment_handler:worker-detail' pk=user.id %}">
                        <img class="avatar avatar-sm my-0 rounded-circle" style="object-fit: cover;"
                             src="{% static 'img/team/'|add:user.username|add:'.jpeg' %}"
                             id="avatar-{{ worker.id }}-0"
                             onerror="placeholderAvatar(this)">
                      </a>
                      <script>
                        function placeholderAvatar(img) {
                          img.src = "{% static 'img/team/avatar-placeholder.jpeg' %}";
                        }
                      </script>
                    </li>
                    <li class="nav-item dropdown ms-lg-auto">
                      <a class="nav-link dropdown-toggle d-flex cursor-pointer align-items-center text-primary" id="userDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="me-2">{{ user.username }}</span>
                      </a>
                      <div class="dropdown-menu dropdown-menu-end mt-0 mt-lg-3 p-3 border-radius-lg" aria-labelledby="userDropdown">
                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="{% url 'assignment_handler:worker-detail' pk=user.id %}">
                          <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-center align-items-center p-0">Personal information</h6>
                        </a>
                        <a class="dropdown-item py-2 ps-3 border-radius-md" target="_blank" href="{% url 'assignment_handler:workers-list' %}">
                          <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-center align-items-center p-0">Rating status</h6>
                        </a>
                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="{% url 'logout' %}">
                          <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-center align-items-center p-0">
                            <i class="fa fa-sign-out me-2" aria-hidden="true"></i>Log Out
                          </h6>
                        </a>
                      </div>
                    </li>
                  {% else %}
                    <li class="nav-item ms-lg-auto">
                      <a class="nav-link nav-link-icon me-2"
                        href="{% url 'login' %}">
                        <i class="fa fa-sign-in me-1"></i>
                        <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign In">Login</p>
                      </a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
          <!-- End Navbar -->
        </div>
      </div>
    </div>